pipeline {
        agent any
        stages
        {
            stage('Run functional test cases') 
            {
                steps 
                {              
                   "test verify -DjenkinsBrowser=${params.browser} -Dcucumber.options=\"--tags ${params.tagName}\""
                }
            }
      	}    
      }